### PR TITLE
all: introduce transport.Transport interface and Transport plugin mechanism

### PR DESCRIPTION
**Pull request by sbinet**
Updates go-zeromq/zmq4#87.

### CODE REVIEW

**Comment by sbinet** [comment]
@space55, what do you think about this infrastructure?
would that fit with the needs for a websocket transport?

**Comment by space55** [comment]
I think it would definitely fit the needs. My only question is if the `Transport` interface concept of passing in your own transport should be used for everything - tcp, udp, ipc, unix, etc., though it does look like it mostly works that way.

I'm a fan!

**Comment by sbinet** [comment]
I did consider removing the default tcp, udp, etc... transports from the "core" zmq4 package.
But as zmq4 already imports "net" it seemed a bit pointless.

Unless there's a big outcry, I'll merge this shortly.
Do you want me to create a dedicated repo (under the go-zeromq organization) to host the websocket based transport?

**Comment by space55** [comment]
Creating a repo specifically for it would likely be best (that way there's an official version)

**Comment by sbinet** [comment]
it's available there:
- https://github.com/go-zeromq/zmq4-transport-plugin

**Pull request merged**
